export interface IUser {
  email: string; // User's email, must be unique and lowercase
  firstName: string; // User's first name, required
  lastName: string; // User's last name, required
  password: string; // Hashed password, required
  verificationCode: string; // Code used for email verification
  passwordResetCode?: string | null; // Code used for resetting password, optional
  verified: boolean; // Indicates if the user's email is verified
  profilePicture?: string; // URL to the user's profile picture, optional
  bio?: string; // User's bio, optional
  posts?: string[]; // References to the user's posts
  followers: number; // Number of followers the user has
  following: number; // Number of users the user is following
  bookmarks?: string[]; // Posts bookmarked by the user
  fav?: string[]; // Posts marked as favorite by the user
  createdAt?: Date; // Timestamp when the user was created (provided by `timestamps: true`)
  updatedAt?: Date; // Timestamp when the user was last updated (provided by `timestamps: true`)
  _id: string; // Unique ID generated by MongoDB
  tempBookmarks: string[];
}

export interface CreatorCardProps {
  creatorData: IUser; // Assuming IUser is defined elsewhere
}
